-- Seed random number generator per thread
math.randomseed(os.time())

local short_ids = {
    "tehLp",
    "mouSw",
    "LVho1",
    "wx87C",
    "lLGNT",
    "ym5TJ",
    "2nq9c",
    "1niNu",
    "vcUtW",
    "KYbWJ",
    "vmjMi",
    "7lZll",
    "559Rl",
    "zt4Wm",
    "s0Ade",
    "nbSRO",
    "uJPfn",
    "uIiSq",
    "47Udk",
    "nr7Yc",
    "sJFMI",
    "QBBqM",
    "FiDMZ",
    "np1vT",
    "3HTaG",
    "EhlCX",
    "U6p0y",
    "REsDO",
    "CJlje",
    "7Vb7q",
    "N3feF",
    "MDm7D",
    "N0lrS",
    "wmlTS",
    "euK5x",
    "ESBdi",
    "iZvlJ",
    "DWPCA",
    "a01NX",
    "sGlDq",
    "33b8A",
    "b89mM",
    "OPy1W",
    "THfjw",
    "HiLKk",
    "GTRLS",
    "rKkDH",
    "gCKKq",
    "iWxK0",
    "2Xrgg",
    "5Hy7T",
    "jSBZI",
    "7eHE3",
    "xYOxt",
    "wYVdd",
    "4VuDG",
    "326rA",
    "ZOrMG",
    "9NIQL",
    "WfvOS",
    "7AlUa",
    "cJRm7",
    "D3RW4",
    "Om0Z6",
    "Q4pTF",
    "ZTGHy",
    "T2OlO",
    "SO60e",
    "woBUq",
    "3bl4v",
    "2Qqy0",
    "pcZJI",
    "YKr9O",
    "PMAd5",
    "LU721",
    "X4Rym",
    "PZDqD",
    "StyTO",
    "tFNyN",
    "GnO4l",
    "FHqb6",
    "ce8Z4",
    "LCdZA",
    "lV3GY",
    "JnnfX",
    "8dk18",
    "clnw9",
    "bmn6H",
    "dc9sg",
    "LgtsC",
    "qsmmC",
    "UcFRj",
    "nsVir",
    "3G6ma",
    "woG0c",
    "eDfE3",
    "F4xVH",
    "bJJUT",
    "obv2v",
    "AE7Rs"
}

request = function()
    local random_index = math.random(1, #short_ids)
    local short_id = short_ids[random_index]
    
    wrk.method = "GET"
    wrk.path = "/short/" .. short_id
    
    return wrk.format()
end

response = function(status, headers, body)
    if status ~= 200 and status ~= 301 and status ~= 302 then
        print("GET /short/ failed with status: " .. status)
    end
end
